spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化物理连接个数，默认值0
      initial-size: 5
      min-idle: 10
      max-active: 20
      time-between-eviction-runs-millis: 2000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      max-wait: 60000
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      test-while-idle: true
      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      validation-query: SELECT 'x'
      #连接池泄露处理
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true

        ##########################################################################
      #
      # 过滤器配置
      #
      ##########################################################################
      # 启用默认配置过滤器
      #      filters: wall,mergeStat,config,slf4j
      filter:
        stat:
          enabled: true
          merge-sql: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: true
            drop-table-allow: false
            truncate-allow: false
      #        commons-log:
      #          connection-close-after-log-enabled: true


      ##########################################################################
      #
      # 监控配置
      #
      ##########################################################################
      aop-patterns: org.mark.demo.*.service.*
      stat-view-servlet:
        allow: 10.88.1.87,127.0.0.1
        #        deny:
        enabled: true
        login-password: 123456
        login-username: mark
        reset-enable: true
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        exclusions: /static/**,*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid,/druid/*
        principal-cookie-name: JSESSIONID
        principal-session-name: username
        profile-enable: true
        session-stat-enable: true
        #        session-stat-max-count:
        url-pattern: /*


##########################################################################
#                                 日志配置
##########################################################################
logging:
  level.root: info
  level.org.apache: info
  level.org.mark: trace
  path: d:\\logs\\
  file: seed.log